[tools]
rust = "1.91"
node = "24"
"aqua:pnpm/pnpm" = 'latest'

[tasks.prep]
run = "uv pip install -e src-tauri"

[tasks.dev]
depends = "prep"
run = "pnpm tauri dev"

[tasks.'build']
run = "uv run ./scripts/build_app.py"

[tasks.'update_dependencies']
run = ['pnpm dlx npm-check-updates -u', 'pnpm install']
